### ISSUE TITLE
Semantic HTML elements

### ISSUE THREAD

**Issue by aubreywullschleger** [DRBJAX/prj-rev-bwfs-dasmoto#1]
Great! I love that you used semantic elements like  `<header>` and `<main>`.  Using semantic elements helps improve the accessibility of your page. Here's info on how semantic elements help with accessibility: https://webflow.com/blog/html5-semantic-elements-and-webflow-the-essential-guide (scroll down to the 'So what are semantic elements good for?' heading) and a list of more semantic elements you can use: http://www.techstrikers.com/HTML5/html5-semantic-elements.php

Example: https://github.com/DRBJAX/prj-rev-bwfs-dasmoto/blob/master/Dasmotos/index.html#L8-L10

**Comment by DRBJAX** [comment]
Thanks.
