### ISSUE TITLE
Closing tags

### ISSUE THREAD

**Issue by aubreywullschleger** [DRBJAX/prj-rev-bwfs-dasmoto#2]
Subtlety for errors!  Be sure all your HTML elements are closed properly.  The opening `<main>` tag is missing it's closing `</main>` tag (line 11).  I would also consider deleting any extra lines that are not consistent with your markup's nesting, indenting, and spacing.

See https://github.com/DRBJAX/prj-rev-bwfs-dasmoto/blob/master/Dasmotos/index.html#L24-L26

**Comment by DRBJAX** [comment]
Ah...what I get for going too fast and not paying attention. Thanks.
