### ISSUE TITLE
Locally stored images

### ISSUE THREAD

**Issue by aubreywullschleger** [DRBJAX/prj-rev-bwfs-dasmoto#3]
Simplify! Consider using locally stored images in your project as this is best practice for production code and will make your page load faster.  To do this you would create a new `images` folder inside your `resources` folder, like this:
![screen shot 2017-08-24 at 7 14 12 pm](https://user-images.githubusercontent.com/11949479/31062936-60dc3290-a6e3-11e7-9a6b-4536cf30c3d5.png)

Then save your images to this new folder, and use your `<img>` tags like this:
`<img src="./resources/images/hacksaw.jpeg" alt="image of hacksaw paint brushes"/>` . 

Also, be sure to use descriptive `alt` attributes on your `<img>` elements as this is best practice and helps with accessibility as well (see above for example).

Example: https://github.com/DRBJAX/prj-rev-bwfs-dasmoto/blob/master/Dasmotos/index.html#L13

**Comment by DRBJAX** [comment]
Thanks. I usually do download images and then either resize / crop using a program, then upload using a local url. I incorrectly assumed CC wanted me to use an absolute path.
