### ISSUE TITLE
Using group selectors

### ISSUE THREAD

**Issue by aubreywullschleger** [DRBJAX/prj-rev-bwfs-dasmoto#4]
Simplify! Consider adding a group selector for any repeated styles in your CSS.  For example, `font-family: Helvetica;` is repeated a few times throughout your CSS.  Instead of repeating this style you should use a group selector for it to make your CSS more concise.

You could use:
```
h1, h2, span {
  font-family: Helvetica;
}
```
Then delete `font-family: Helvetica;` from those individual selectors. This practice helps keep your CSS concise.

**Comment by DRBJAX** [comment]
Great tip. Should have went through and refactored my own code for efficiency. Laziness is the mother of sloppiness I guess. I'll slow down on next projects and take the time to do so.
