### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by aubreywullschleger** [DRBJAX/prj-rev-bwfs-dasmoto#5]
Grade: Meets expectations

Summary:
Great work with this project! I love your organized, semantic HTML. Keep it up! 

A few things to work on here: 1. making sure all your elements are properly closed, 2. using locally stored images with descriptive `alt` attributes for your `<img>` elements, and 3. making your CSS more concise by adding group selectors for any repeated styles.

Next, as a stretch goal, I challenge you to research and implement media queries to make your page responsive for all screen widths.  This is a challenge I think you are ready for based on your work with this project!  Here are a couple resources to get you started: https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries and https://css-tricks.com/snippets/css/media-queries-for-standard-devices/

**Comment by DRBJAX** [comment]
Got it. Will re-do, re-commit and push back up when done.
